version: '3.8'
networks:
  net:
    external: false
volumes:
  postgres-db:
    external: false
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ordenycompra
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=ordenycompra
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - PGUSER=postgres
      - PGADMIN_DEFAULT_EMAIL=postgres@postgresql.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 2s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
    networks:
      - net